"""Output writing — compose.yml, Caddyfile, warnings."""

import os
import sys

import yaml


def write_compose(services: dict, config: dict, output_dir: str,
                  compose_file: str = "compose.yml") -> None:
    """Write compose file."""
    compose = {}
    if config.get("name"):
        compose["name"] = config["name"]
    compose["services"] = services

    # Add top-level named volumes
    named_volumes = {}
    for vol_name, vol_cfg in config.get("volumes", {}).items():
        if isinstance(vol_cfg, dict) and "host_path" not in vol_cfg:
            named_volumes[vol_name] = vol_cfg
    if named_volumes:
        compose["volumes"] = named_volumes

    # External network override
    ext_network = config.get("network")
    if ext_network:
        compose["networks"] = {"default": {"external": True, "name": ext_network}}

    has_sidecars = any("container_name" in s for s in services.values())

    path = os.path.join(output_dir, compose_file)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by helmfile2compose — do not edit manually\n")
        if has_sidecars:
            f.write("# WARNING: Sidecar containers use container_name for network sharing.\n")
            f.write("# Do not use 'docker compose -p' — rename via helmfile2compose.yaml instead.\n")
        yaml.dump(compose, f, default_flow_style=False, sort_keys=False)
    print(f"Wrote {path}", file=sys.stderr)


def _write_caddy_reverse_proxy(f, entry: dict, indent: str = "\t") -> None:
    """Write a reverse_proxy directive, with TLS transport if upstream is HTTPS."""
    scheme = entry.get("scheme", "http")
    upstream = entry["upstream"]
    if scheme != "https":
        f.write(f"{indent}reverse_proxy {upstream}\n")
        return
    ca_secret = entry.get("server_ca_secret", "")
    f.write(f"{indent}reverse_proxy https://{upstream} {{\n")
    f.write(f"{indent}\ttransport http {{\n")
    if ca_secret:
        sni = entry.get("server_sni", "")
        if sni:
            f.write(f"{indent}\t\ttls_server_name {sni}\n")
        f.write(f"{indent}\t\ttls_trust_pool file"
                f" /etc/caddy/certs/{ca_secret}/ca.crt\n")
    else:
        f.write(f"{indent}\t\ttls_insecure_skip_verify\n")
    f.write(f"{indent}\t}}\n")
    f.write(f"{indent}}}\n")


def _write_caddy_host_block(f, host: str, host_entries: list[dict],
                            tls_internal: bool = False) -> None:
    """Write a single Caddy host block (specific paths first, catch-all last)."""
    specific = [e for e in host_entries if e["path"] and e["path"] != "/"]
    catchall = [e for e in host_entries if not e["path"] or e["path"] == "/"]
    f.write(f"{host} {{\n")
    if tls_internal:
        f.write("\ttls internal\n")
    for entry in specific:
        f.write(f"\thandle {entry['path']}* {{\n")
        if entry.get("strip_prefix"):
            f.write(f"\t\turi strip_prefix {entry['strip_prefix']}\n")
        for directive in entry.get("extra_directives", []):
            f.write(f"\t\t{directive}\n")
        _write_caddy_reverse_proxy(f, entry, indent="\t\t")
        f.write("\t}\n")
    for entry in catchall:
        for directive in entry.get("extra_directives", []):
            f.write(f"\t{directive}\n")
        _write_caddy_reverse_proxy(f, entry)
    f.write("}\n\n")


def write_caddyfile(entries: list[dict], output_dir: str,
                    config: dict | None = None,
                    filename: str = "Caddyfile") -> None:
    """Write Caddyfile."""
    if not entries:
        return

    path = os.path.join(output_dir, filename)
    replacements = (config or {}).get("replacements", [])
    by_host: dict[str, list[dict]] = {}
    for e in entries:
        # Apply replacements to upstream names (e.g. service alias rewrites)
        if replacements:
            for r in replacements:
                e["upstream"] = e["upstream"].replace(r["old"], r["new"])
        by_host.setdefault(e["host"], []).append(e)

    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by helmfile2compose — do not edit manually\n\n")
        caddy_email = (config or {}).get("caddy_email")
        if caddy_email:
            f.write(f"{{\n\temail {caddy_email}\n}}\n\n")
        tls_internal = bool((config or {}).get("caddy_tls_internal"))
        for host, host_entries in by_host.items():
            _write_caddy_host_block(f, host, host_entries, tls_internal)
    print(f"Wrote {path}", file=sys.stderr)


def emit_warnings(warnings: list[str]) -> None:
    """Print all warnings to stderr."""
    for w in warnings:
        print(f"⚠ {w}", file=sys.stderr)
